### ISSUE TITLE
Add tag/describe in the repo

### ISSUE THREAD

**Issue by sl1pkn07** [roderickc/wine-vulkan#17]
`git describe --long --tags` do nothing in this repo

please add tags/describe

greetings

**Comment by roderickc** [comment]
My repo is just regular Wine with some commits on top. I'm not doing any tagging. I think wine the wine repo itself is not doing what you are after. Why are you interested in this info?

**Comment by ChristophHaag** [comment]
One reason would be that the wine-git AUR package uses the tags to generate the package version: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wine-git#n110
and it generates an error when the version is empty so if you edit it to build wine-vulkan instead, you need to change that too (I did in my wine-vulkan-git package).

That issue would simply be solved by pulling the tags from upstream wine.

**Comment by roderickc** [comment]
Hmm, I thought I had at least preserved tags. Maybe I need to push the old tags there were. Although this isn't really useful as none of the regular wine tags have my code.
Not sure yet what I'm going to do. The repo is mostly a development branch and there are a lot of rebases / force pushes happening. Hopefully as of today all my code will be in regular Wine. From time to time I may add some experimental stuff to wine-vulkan, but for most users regular Wine is probably best to use.

**Comment by roderickc** [comment]
I did a git push --tags. Let me know if this helped.

**Comment by ChristophHaag** [comment]
The versioning scheme is typically something [git tag].r[number of commits since git tag].[commit hash] so the version number would show which mainline wine version the patches are currently based on, how many commits you added and specifically which commit is currently used.

Since mainline wine accepted the patches it's a moot point, so I have not tested it but https://github.com/roderickc/wine-vulkan/tags shows all the tags so it should be solved.

**Comment by sl1pkn07** [comment]
yep. `git describe --long --tags`  works now

```
└───╼  git describe --long --tags
wine-3.3-266-g18556942eb
```

greetings
